### ISSUE TITLE
Auto append branch to version

### ISSUE THREAD

**Issue by benpullman** [CCMS-UCSD/CCMSDeployments#16]
Thinking it might make sense to append the development branch name to the version number, for cases when people are doing development on a different branch.  Could get tricky when the head is detached, but I think it'll be handleable.

**Comment by mwang87** [comment]
This will only be done for deploy-debug and not production.

**Comment by benpullman** [comment]
Would it make sense to not allow deployment to production on a non-master/non-release hash branch? I.e. production ready if branch is master or if detached head is in the .gitmodules directory. 

If these criteria are satisfied, 1. will not attach branch name to version and 2. will allow for deployment to productionv

**Comment by mwang87** [comment]
I think this is too much complexity to manage on the production side. I don't foresee a use for this.

**Comment by benpullman** [comment]
I guess the only use would be accidentally releasing a branch, but its true, this might make sense in certain situations.
