### ISSUE TITLE
Need to include a "deploy all" or equivalent

### ISSUE THREAD

**Issue by benpullman** [CCMS-UCSD/CCMSDeployments#2]
Right now the method for deploying multiple workflows requires writing a long and mostly repeated fab command.

**Comment by mwang87** [comment]
One of the issues we have to contend with is how do we know what is the workflow name and tool folder name. Currently we keep this in the makefile, maybe its better as a yaml, since then a python script can read that?

**Comment by benpullman** [comment]
I should have added - our thinking now involves including it in the yaml for each deployment.  Maybe just the folder names, then a script go into each folder and parse the associated Makefiles?

**Comment by mwang87** [comment]
Yeah, I think thats a reasonable solution. Parsing the makefile should be pretty straightforward.

**Comment by benpullman** [comment]
I agree - I'll implement this tomorrow.  I also would then propose moving the deployment yml files out of this repository and into the workflow specific repository, since these will be updated on the release schedule of the workflows, not the deployment procedures themselves.
